words = [
    "akamai",
    "arrayable",
    "autocmd",
    "autoincremented",
    "bayphoto",
    "behaviour",
    "cachekey",
    "checkboxes",
    "creditcard",
    "cwd",
    "delists",
    "docblocks",
    "firstname",
    "formatters",
    "function",
    "gitcommit",
    "gnormal",
    "incoterm",
    "initializable",
    "iryna",
    "issets",
    "laravel",
    "lastname",
    "lazyvim",
    "mimetypes",
    "mise",
    "morphable",
    "multibyte",
    "neovim",
    "nette",
    "noremap",
    "phpcs",
    "phpspec",
    "phpstan",
    "phpunit",
    "plantuml",
    "postalcode",
    "reassociate",
    "reindexing",
    "retryable",
    "ruleset",
    "shouldbe",
    "sku",
    "swoole",
    "tkey",
    "traefik",
    "tty",
    "tval",
    "typehint",
    "undeletes",
    "unsets",
    "vtsls",
    "xdebug",
    "zipcode",
]
