words = [
    "akamai",
    "arrayable",
    "autocmd",
    "autoincremented",
    "bayphoto",
    "bcmath",
    "behaviour",
    "cachekey",
    "checkboxes",
    "creditcard",
    "ctype",
    "cwd",
    "dba",
    "delists",
    "docblocks",
    "evalcache",
    "exif",
    "firstname",
    "formatters",
    "function",
    "gitcommit",
    "gmp",
    "gnormal",
    "hipatterns",
    "imagick",
    "imap",
    "incoterm",
    "initializable",
    "intelephense",
    "intl",
    "iryna",
    "issets",
    "laravel",
    "lastname",
    "lazyvim",
    "luasnip",
    "mimetypes",
    "mise",
    "morphable",
    "multibyte",
    "mysqli",
    "navic",
    "neovim",
    "nette",
    "noremap",
    "nvim",
    "oci",
    "octo",
    "openssl",
    "pcache",
    "pcntl",
    "pcre",
    "pdo",
    "pgsql",
    "phpcbf",
    "phpcs",
    "phpspec",
    "phpstan",
    "phpunit",
    "plantuml",
    "postalcode",
    "pspell",
    "reassociate",
    "reindexing",
    "retryable",
    "ruleset",
    "shmop",
    "shouldbe",
    "sku",
    "snmp",
    "spl",
    "superglobals",
    "swoole",
    "sysvmsg",
    "sysvsem",
    "sysvshm",
    "tealdeer",
    "tkey",
    "traefik",
    "tty",
    "tval",
    "typehint",
    "undeletes",
    "unsets",
    "vtsls",
    "xdebug",
    "xmlreader",
    "yanky",
    "zipcode",
]
