words = [
    "akamai",
    "arrayable",
    "autocmd",
    "autoincremented",
    "autoindent",
    "autoindenting",
    "babelrc",
    "bayphoto",
    "bcmath",
    "behaviour",
    "bufferline",
    "cabbr",
    "cachekey",
    "cfilter",
    "checkboxes",
    "cmdheight",
    "colorcolumn",
    "containerfile",
    "creditcard",
    "croqjt",
    "cspell",
    "cterm",
    "ctype",
    "curdir",
    "cwd",
    "dba",
    "delists",
    "docblocks",
    "dosini",
    "eob",
    "evalcache",
    "exif",
    "exrc",
    "fillchars",
    "firstname",
    "foldcolumn",
    "foldlevel",
    "foldtext",
    "formatoptions",
    "formatters",
    "function",
    "getscript",
    "gitcommit",
    "gmp",
    "gnormal",
    "grepformat",
    "grepprg",
    "guicursor",
    "guifont",
    "gzip",
    "higroup",
    "hipatterns",
    "hlsearch",
    "iabbrev",
    "imagick",
    "imap",
    "inccommand",
    "incoterm",
    "initializable",
    "intelephense",
    "intl",
    "iryna",
    "issets",
    "joinspaces",
    "keytrans",
    "laravel",
    "lastname",
    "laststatus",
    "lazyredraw",
    "lazyvim",
    "listchars",
    "logipat",
    "luasnip",
    "mimetypes",
    "minlines",
    "mise",
    "morphable",
    "mousemoveevent",
    "multibyte",
    "mysqli",
    "navic",
    "neovide",
    "neovim",
    "netrw",
    "nette",
    "noice",
    "norelative",
    "noremap",
    "nvim",
    "oci",
    "octo",
    "openssl",
    "packadd",
    "pcache",
    "pcntl",
    "pcre",
    "pdo",
    "pgsql",
    "phpcbf",
    "phpcs",
    "phpspec",
    "phpstan",
    "phpunit",
    "plantuml",
    "postalcode",
    "pspell",
    "psr",
    "pumblend",
    "reassociate",
    "reindexing",
    "relativenumber",
    "relnumber",
    "retryable",
    "rrhelper",
    "ruleset",
    "runtimepath",
    "scrolloff",
    "sessionoptions",
    "shmop",
    "shouldbe",
    "showtabline",
    "sku",
    "smartindent",
    "snmp",
    "spellfile",
    "spl",
    "splitkeep",
    "statusline",
    "superglobals",
    "swapfile",
    "swoole",
    "sysvmsg",
    "sysvsem",
    "sysvshm",
    "tabpages",
    "tealdeer",
    "textwidth",
    "timeoutlen",
    "tkey",
    "traefik",
    "tty",
    "tval",
    "typehint",
    "undeletes",
    "unsets",
    "updatetime",
    "vimball",
    "vimgrep",
    "vtsls",
    "winblend",
    "winborder",
    "winsize",
    "xdebug",
    "xmlreader",
    "yanky",
    "zipcode",
]
