---
customCommands:
  - description: "git spice stack restack"
    context: "localBranches"
    command: "git-spice stack restack"
  - description: "git spice stack edit"
    context: "localBranches"
    command: "git-spice stack edit"
  - description: "git spice stack publish"
    context: "localBranches"
    command: "git-spice repo sync && git-spice stack restack && git-spice stack submit"
  - description: "git spice branch create"
    context: "localBranches"
    prompts:
      - type: "input"
        title: "What is the new branch name?"
        key: "BranchName"
        initialValue: ""
    command: "git-spice branch create {{.Form.BranchName}}"
  - description: "git spice branch track"
    context: "localBranches"
    command: "git-spice branch track"
  - description: "git spice branch checkout"
    context: "localBranches"
    command: "git-spice branch checkout"
  - description: "git spice branch split"
    context: "localBranches"
    command: "git-spice branch split"
  - description: "git spice branch graft onto"
    context: "localBranches"
    command: "git-spice upstack onto"
  - description: "git branch clean merged"
    context: "localBranches"
    command: "git checkout develop && git pull && git cleanmerged && git checkout -"
  # TODO: not working
  - description: "git tag semantic versions"
    context: "localBranches"
    command: "git semver"
  - description: "fetch"
    key: "<c-f>"
    context: "localBranches"
    command: "git fetch"
git:
  mainBranches:
    - develop
    - main
    - master
  pagers:
    - pager: delta --diff-so-fancy --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
