---
customCommands:
  - description: "git spice stack restack"
    context: "commits"
    command: "git-spice stack restack"
  - description: "git spice stack edit"
    context: "commits"
    command: "git-spice stack edit"
  - description: "git spice stack publish"
    context: "commits"
    command: "git-spice repo sync && git-spice stack restack && git-spice stack submit"
  - description: "git spice branch create"
    context: "commits"
    prompts:
      - type: "input"
        title: "What is the new branch name?"
        key: "BranchName"
        initialValue: ""
    command: "git-spice branch create {{.Form.BranchName}}"
  - description: "git spice branch track"
    context: "commits"
    command: "git-spice branch track"
  - description: "git spice branch checkout"
    context: "commits"
    command: "git-spice branch checkout"
  - description: "git spice branch split"
    context: "commits"
    command: "git-spice branch split"
  - description: "git spice branch graft onto"
    context: "commits"
    command: "git-spice upstack onto"
